apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent
  namespace: playit
spec:
  replicas: 0
  selector:
    matchLabels:
      app: playit-agent
  template:
    metadata:
      labels:
        app: playit-agent
    spec:
      containers:
        - name: playit
          image: ghcr.io/playit-cloud/playit-agent:1.0
          imagePullPolicy: Always
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: secret-key
