apiVersion: v1
kind: Secret
metadata:
    name: secret
    namespace: playit
type: Opaque
stringData:
    secret-key: ENC[AES256_GCM,data:ayDNB8yv/rnS67O+UE7fz47M+BtnnQW/MlfKc4exukTVqE7TRGJkY3qTbuopneo7iIPGtPF3gckIDVTJ11mdgQ==,iv:600RfQ/j5FV5g37/HWtdrmlEK1u3aXsxdjdueoOE13U=,tag:2gPU35Qw6MdRueKBqjNgnA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkaG5BV3BXRVBNUEpKd3J2
            VUExcEViaUdSdVNBZkJHVDBPc2JncGdNRW13CmFxckpQRWFmM2Q4cE56ZkpwMjlC
            YUdwTW44V1FuZGpGRlN6bDZ0bmJsM28KLS0tIHZpbUZIZmdkV0Jwdlp1enBpcFV1
            NVhkdGgyN3pVdEViN2xVbDduSXAwNWsKQ4mRhoL5EJ9zlsmzFjy/tfIehur+9Wkm
            iuOFMIS/NeAKGNiRGXFjhtPsFNoavnXZiUCbHZO2wLNwEqDJC8yDRQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age129flpnac62c0cqjhzupx6rkrqe7etjn3jm53zhuu923mt05xluwsy6r9sd
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-23T18:26:07Z"
    mac: ENC[AES256_GCM,data:tAmSDVr1w0JFvlGS0qCcfGbYao452JR4DoE9hZa7S4RYdpKEF//xQDI2ISiRFJ/EXt8lQZAEoN3IIHyAmRBDcrL1b0lTh0blYeDb+Pa9LehjSVJsYtDhVfDRpMFL8ziktSHWR0WvXWvUsR53dksko9rag8EusyI6ys/xerwayKA=,iv:cyCyUsxrtdmazTZnt2kNG62rVd22YycYLjaZjP5yCZg=,tag:6GKGgoI27gUzyMBaKOhoHQ==,type:str]
    version: 3.13.1
