apiVersion: v1
kind: Service
metadata:
  name: service
  namespace: playit
  labels:
    app: playit-agent
spec:
  ports:
    - name: port-1001-tcp
      port: 1001
      targetPort: 1001
      protocol: TCP
    - name: port-1001-udp
      port: 1001
      targetPort: 1001
      protocol: UDP
    - name: port-1002-tcp
      port: 1002
      targetPort: 1002
      protocol: TCP
    - name: port-1002-udp
      port: 1002
      targetPort: 1002
      protocol: UDP
    - name: port-1003-tcp
      port: 1003
      targetPort: 1003
      protocol: TCP
    - name: port-1003-udp
      port: 1003
      targetPort: 1003
      protocol: UDP
    - name: port-1004-tcp
      port: 1004
      targetPort: 1004
      protocol: TCP
    - name: port-1004-udp
      port: 1004
      targetPort: 1004
      protocol: UDP
    - name: port-1005-tcp
      port: 1005
      targetPort: 1005
      protocol: TCP
    - name: port-1005-udp
      port: 1005
      targetPort: 1005
      protocol: UDP
    - name: minecraft-java
      port: 25565
      targetPort: 25565
      protocol: TCP
  selector:
    app: playit-agent
  type: ClusterIP